// TermsAgreementDialog.vue
<template>
  <v-dialog v-model="dialog" persistent :fullscreen="smAndDown" class="terms-dialog" :width="smAndDown? 'auto':'70vw'" :max-width="smAndDown? '100%': '800px'" :height="smAndDown ? 'auto' : '60%'">
    <v-card>
      <v-toolbar color="#002538" dark :height="smAndDown? '120': '64'">
        <v-toolbar-title class="text-h5 text-white px-5 text-uppercase" :style="{ width: smAndDown ? 'auto' : '100%'}">
          WELCOME TO OUR AI ASSISTANT (BETA VERSION)
        </v-toolbar-title>
      </v-toolbar>

      <v-card-text class="pt-4 terms-content">
        <h3 class="text-subtitle-1 font-weight-bold mb-2">Disclaimer for Test Product Use</h3>
        <p class="mb-4">
          CAUTION: YOU ARE PARTICIPATING IN THE TESTING OF A PRELIMINARY VERSION OF
          THE PHARMACHAT / PHOX CHAT TOOL FOR PURPOSES OF PRODUCT DEVELOPMENT AND
          IMPROVEMENT. THIS PRODUCT IS LIKELY TO GENERATE ERRORS AND INCORRECT
          RESULTS.
        </p>
        <p class="mb-4">
          <a target="_blank" href="https://cdntor.phox.app/phoxchat/chat_disclaimer.mp4">WATCH THE DISCLAIMER VIDEO HERE</a>
        </p>
        <p class="mb-4">
          RESULTS AND OUTPUTS PROVIDED BY THIS PRODUCT MUST NOT BE RELIED UPON
          WITHOUT VERIFICATION BY A PHARMACIST. PARTICIPATION IN THIS TEST AND USE OF
          THIS PRODUCT IS AT YOUR OWN RISK.
        </p>
        <p class="mb-4">By using this test version of PharmaChat / PHOX Chat (the "Product"), you agree to the following terms
          and conditions of this disclaimer for use of the Product during this testing phase (this
          "Disclaimer"):</p>

        <h3 class="text-subtitle-1 font-weight-bold mb-2">1. Test Acknowledgment:</h3>
        <p class="mb-4">This Product is currently in testing phase, meaning it is still under development and subject to ongoing improvements. DURING THIS TESTING PHASE, THE PRODUCT MAY CONTAIN ERRORS, BUGS, OR INCOMPLETE FEATURES, AND FEEDBACK PROVIDED BY USERS WILL BE USED TO REFINE AND ENHANCE THE PRODUCT.</p>
        <p class="mb-4">Users should understand that the Product is not the final version, and changes may occur over time based on feedback and testing results. The duration of the testing phase is undetermined and may be terminated at any time without notice.</p>

        <h3 class="text-subtitle-1 font-weight-bold mb-2">2. Accuracy and Reliability:</h3>
        <p class="mb-4">DO NOT RELY ON THE OUTPUTS OF THIS PRODUCT. While we strive to provide accurate and up-to-date information, the responses and content generated by this Product may not be reliable or complete. This Product is intended for informational purposes only, but is not intended to be relied upon and is not designed to serve as a source of truth or fact. Users are expected to exercise their clinical judgment in all instances, verify information with other trusted resources, and make decisions based on a broader context. The Product is not a substitute for professional medical, legal, or other regulated advice.</p>
        <p class="mb-4">By using the Product, you acknowledge and agree that: (i) we may use features and functionalities that are powered by artificial intelligence or machine learning technologies ("AI Technologies") to perform certain services and, given the changing nature of AI Technologies, we cannot guarantee that outputs and responses generated through use of the Product ("Outputs") will be accurate or factual; (ii) you will not rely or allow your end-users to rely on Outputs as a source of truth or factual information, or as a substitute for professional advice; (iii) you will evaluate Outputs for accuracy and appropriateness for applicable use in each case; (iv) Outputs may have different results based on the formulation of questions or the information provided as input; and (v) you will not use or allow your end-users to use the Product to generate Outputs that violate another person's rights, including, without limitation, by way of an infringement of intellectual property rights.</p>

        <h3 class="text-subtitle-1 font-weight-bold mb-2">3. User Responsibility:</h3>
        <p class="mb-4">It is the responsibility of the user to apply their own professional judgment and expertise when using this Product. Any decisions made based on the responses generated by the Product must be independently verified by the user, and the user should not rely solely on the Product for decision-making. You agree that you fully release and will not hold the Canadian Pharmacists Association (CPhA) ("CPhA"), Pharma Guide Inc. ("PharmaGuide"), or their respective affiliates, partners, employees, or agents liable for any errors, omissions, or inaccuracies in the information provided by the Product.</p>
        <p class="mb-4">The Product does not, and is not intended to, replace any pharmacists or clinical providers, and is not intended to be used to make any medical diagnoses. The Product and Outputs provided in connection therewith are not a substitute for the competent analysis and professional judgment of a healthcare professional and are not intended to replace medical consultation, examination, record review, or applicable drug assessments. YOU ARE RESPONSIBLE FOR THE FINAL REVIEW OF OUTPUTS GENERATED BY THE PRODUCT AND ALL DECISION-MAKING THEREIN. THE PROFESSIONAL DUTY TO ANY PATIENTS IN THE PROVISION OF HEALTH CARE SERVICES REMAINS SOLELY WITH YOU AND NOT WITH CPHA OR PHARMAGUIDE.</p>

        <h3 class="text-subtitle-1 font-weight-bold mb-2">4. No Liability:</h3>
        <p class="mb-4">IN NO EVENT SHALL CPHA, PHARMAGUIDE OR ANY OF THEIR RESPECTIVE AFFILIATES OR ITS OR THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, SUBCONTRACTORS, MEMBERS, SHAREHOLDERS, LEGAL REPRESENTATIVES, AGENTS, SUCCESSORS OR ASSIGNS (COLLECTIVELY "REPRESENTATIVES") BE LIABLE FOR: (A) LOSS OF REVENUES, PROFITS, CONTRACTS, BUSINESS, GOODWILL OR ANTICIPATED SAVINGS, OR (B) ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE, EXEMPLARY OR OTHER LOSSES OR DAMAGE WHATSOEVER, WHETHER IN CONTRACT, TORT OR OTHERWISE (INCLUDING IN EACH CASE NEGLIGENCE), EVEN IF SUCH LOSSES WERE REASONABLY FORESEEABLE OR CPHA, PHARMAGUIDE OR ANY OF THEIR RESPECTIVE AFFILIATES OR ITS OR THEIR REPRESENTATIVES HAD BEEN ADVISED OF THE POSSIBILITY OF THE OTHER PARTY INCURRING THE SAME.</p>

        <h3 class="text-subtitle-1 font-weight-bold mb-2">5. Feedback Collection:</h3>
        <p class="mb-4">During the testing phase, CPhA and PharmaGuide may collect data, including user feedback, error reports, and usage patterns, to improve the Product. By using this Product, you consent to the collection and use of this data for product refinement purposes. Any suggestions or feedback you provide may be used without compensation or acknowledgment, and you waive any claim to any intellectual property rights or compensation for your suggestions or feedback, and hereby assign all such rights to CPhA and PharmaGuide. We will have full discretion to determine whether or not to proceed with the development of any requested enhancements, new features or functionality.</p>

        <h3 class="text-subtitle-1 font-weight-bold mb-2">6. Acceptance and Amendment of Disclaimer:</h3>
        <p class="mb-4">By using this Product, you agree to this Disclaimer. We may amend, adapt or supplement this Disclaimer at any time without notice. Your continued use of the Product constitutes your acceptance of this Disclaimer, as amended. If you do not agree with this Disclaimer, you must immediately stop using the Product.</p>

        <h3 class="text-subtitle-1 font-weight-bold mb-2">7. Professional and Legal Use:</h3>
        <p class="mb-4">The Product is intended to serve as an educational resource. The Outputs generated by this Product should not be interpreted as legal, medical, or professional advice and should not be used as a substitute for such advice. Users are expected to comply with all applicable laws, regulations, and professional standards when using the Product. CPhA and PharmaGuide are not responsible for ensuring that the content or Outputs generated comply with applicable laws or professional guidelines. The Product should only be used by medical professionals or healthcare providers. Patient assessment requires professional knowledge and judgment beyond the scope of the Product.</p>

        <h3 class="text-subtitle-1 font-weight-bold mb-2">8. Modifications and Termination:</h3>
        <p class="mb-4">CPhA and PharmaGuide reserve the right to modify, suspend, or discontinue the Product at any time without notice. Updates or changes to the Product may include changes to its features, functionality, or content.</p>
        <p class="mb-4">CPhA and PharmaGuide may terminate your access to the Product without notice at any time for any reason, including but not limited to if you violate any terms of this Disclaimer, or for no reason.</p>

        <h3 class="text-subtitle-1 font-weight-bold mb-2">9. DISCLAIMER OF WARRANTIES:</h3>
        <p class="mb-4">THIS TEST PRODUCT IS PROVIDED "AS IS" AND "AS AVAILABLE" AND WITHOUT ANY WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING ALL STATUTORY WARRANTIES AND CONDITIONS. CPHA AND PHARMAGUIDE MAKE NO WARRANTIES REGARDING THE ACCURACY, RELIABILITY, COMPLETENESS, OR SUITABILITY OF THE PRODUCT FOR ANY PARTICULAR PURPOSE. ALL IMPLIED WARRANTIES AND CONDITIONS, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT, ARE HEREBY DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, CPHA AND PHARMAGUIDE DO NOT WARRANT THAT THE PRODUCT IS ERROR-FREE OR THAT THE PRODUCT WILL OPERATE WITHOUT INTERRUPTION. THE PRODUCT MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS. CPHA AND PHARMAGUIDE ARE NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES OR OTHER DAMAGES RESULTING FROM SUCH PROBLEMS. CPHA AND PHARMAGUIDE DO NOT WARRANT OR GUARANTEE THAT THE OUTPUTS OBTAINED THROUGH THE PRODUCT WILL BE ACCURATE, RELEVANT, COMPLETE, OR UP TO DATE. CPHA AND PHARMAGUIDE ARE NOT LIABLE OR RESPONSIBLE FOR, AND HEREBY EXPRESSLY DISCLAIM, UNDER ANY CIRCUMSTANCES: (A) HOW THE PRODUCT IS USED BY YOU OR YOUR END-USERS, (B) HOW YOU USE ANY INFORMATION, OUTPUTS OR DATA OBTAINED THROUGH THE PRODUCT, OR (C) ANY CONSEQUENCES THEREOF.</p>

        <h3 class="text-subtitle-1 font-weight-bold mb-2">10. General:</h3>
        <p class="mb-4">This Disclaimer shall be governed by and construed in accordance with the laws of the Province of Ontario and the laws of Canada applicable therein. You agree to irrevocably attorn to the exclusive jurisdiction of the courts located in Ottawa, Ontario. If any part of this Disclaimer is held to be invalid or otherwise unenforceable, the provision shall no longer form part of this Disclaimer.</p>
        <p class="mb-4">By continuing to use this Product, you confirm that you have read, understood, and agree to this Disclaimer. If you do not agree, you must discontinue use of the Product immediately.</p>

      </v-card-text>

      <div class="px-4 py-2">
        <v-checkbox
          v-model="acknowledged"
          label="I acknowledge the above and agree to participate in feedback collection."
          color="#52B8C5"
          hide-details
        ></v-checkbox>
      </div>

      <v-card-actions class="justify-center px-7 pt-0">
        <v-btn
          color="#52B8C5"
          variant="flat"
          :disabled="!acknowledged"
          @click="confirmAndClose"
          class="text-white mb-3"
          block
        >
          CONFIRM AND PROCEED
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup>
import { ref, watch } from 'vue';
import { useDisplay } from 'vuetify';

const props = defineProps({
  modelValue: {
    type: Boolean,
    required: true
  }
});

const emit = defineEmits(['update:modelValue']);

const { smAndDown } = useDisplay();

const dialog = ref(false);
const acknowledged = ref(false);

watch(() => props.modelValue, (newVal) => {
  dialog.value = newVal;
});

watch(dialog, (newVal) => {
  if (!newVal) {
    emit('update:modelValue', false);
  }
});

const confirmAndClose = () => {
  if (acknowledged.value) {
    dialog.value = false;
    acknowledged.value = false;
  }
};
</script>

<style lang="scss" scoped>
.v-card-title {
  padding: 16px;
}

.terms-dialog {
  .terms-content {
    overflow-y: auto;
  }

  a {
    color: #52B8C5;
    text-decoration: none;
  }

  a:hover {
    text-decoration: underline;
  }
}

:deep(.v-toolbar-title__placeholder) {
  text-wrap: auto !important;
  white-space: normal;
}
</style>

// components/TermsAgreementDialog.tsx
"use client";

import { useEffect, useState } from "react";

interface TermsAgreementDialogProps {
  isOpen: boolean;
  onClose: () => void;
}

export function TermsAgreementDialog({
  isOpen,
  onClose,
}: TermsAgreementDialogProps) {
  const [acknowledged, setAcknowledged] = useState(false);
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const checkMobile = () => setIsMobile(window.innerWidth < 640);
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  useEffect(() => {
    // Prevent body scroll when dialog is open
    if (isOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
    return () => {
      document.body.style.overflow = "";
    };
  }, [isOpen]);

  const handleConfirm = () => {
    if (acknowledged) {
      setAcknowledged(false); // Reset for next time
      onClose();
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div
        className={`flex flex-col bg-white dark:bg-slate-900 shadow-2xl ${
          isMobile ? "h-full w-full" : "max-h-[90vh] w-full max-w-6xl rounded-2xl"
        }`}
      >
        {/* Header */}
        <div
          className={`flex items-center px-6 text-white ${
            isMobile ? "py-6" : "py-4"
          }`}
          style={{ backgroundColor: "#002538" }}
        >
          <h2 className="text-lg font-semibold uppercase sm:text-xl">
            Welcome to Our AI Assistant (Beta Version)
          </h2>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-4 text-slate-700 dark:text-slate-300">
          <div className="space-y-4">
            <section>
              <h3 className="mb-2 text-base font-bold text-slate-900 dark:text-slate-100">
                Disclaimer for Test Product Use
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                CAUTION: YOU ARE PARTICIPATING IN THE TESTING OF A PRELIMINARY VERSION OF THE PHARMACHAT / PHOX CHAT TOOL FOR PURPOSES OF PRODUCT DEVELOPMENT AND IMPROVEMENT. THIS PRODUCT IS LIKELY TO GENERATE ERRORS AND INCORRECT RESULTS.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                <a
                  target="_blank"
                  rel="noopener noreferrer"
                  href="https://cdntor.phox.app/phoxchat/chat_disclaimer.mp4"
                  className="underline hover:no-underline"
                  style={{ color: "#52B8C5" }}
                >
                  WATCH THE DISCLAIMER VIDEO HERE
                </a>
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                RESULTS AND OUTPUTS PROVIDED BY THIS PRODUCT MUST NOT BE RELIED UPON WITHOUT VERIFICATION BY A PHARMACIST. PARTICIPATION IN THIS TEST AND USE OF THIS PRODUCT IS AT YOUR OWN RISK.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                By using this test version of PharmaChat / PHOX Chat (the &quot;Product&quot;), you agree to the following terms and conditions of this disclaimer for use of the Product during this testing phase (this &quot;Disclaimer&quot;):
              </p>
            </section>

            <section>
              <h3 className="mb-2 text-base font-bold text-slate-900 dark:text-slate-100">
                1. Test Acknowledgment:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                This Product is currently in testing phase, meaning it is still under development and subject to ongoing improvements. DURING THIS TESTING PHASE, THE PRODUCT MAY CONTAIN ERRORS, BUGS, OR INCOMPLETE FEATURES, AND FEEDBACK PROVIDED BY USERS WILL BE USED TO REFINE AND ENHANCE THE PRODUCT.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                Users should understand that the Product is not the final version, and changes may occur over time based on feedback and testing results. The duration of the testing phase is undetermined and may be terminated at any time without notice.
              </p>
            </section>

            <section>
              <h3 className="mb-2 text-base font-bold text-slate-900 dark:text-slate-100">
                2. Accuracy and Reliability:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                DO NOT RELY ON THE OUTPUTS OF THIS PRODUCT. While we strive to provide accurate and up-to-date information, the responses and content generated by this Product may not be reliable or complete. This Product is intended for informational purposes only, but is not intended to be relied upon and is not designed to serve as a source of truth or fact. Users are expected to exercise their clinical judgment in all instances, verify information with other trusted resources, and make decisions based on a broader context. The Product is not a substitute for professional medical, legal, or other regulated advice.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                By using the Product, you acknowledge and agree that: (i) we may use features and functionalities that are powered by artificial intelligence or machine learning technologies (&quot;AI Technologies&quot;) to perform certain services and, given the changing nature of AI Technologies, we cannot guarantee that outputs and responses generated through use of the Product (&quot;Outputs&quot;) will be accurate or factual; (ii) you will not rely or allow your end-users to rely on Outputs as a source of truth or factual information, or as a substitute for professional advice; (iii) you will evaluate Outputs for accuracy and appropriateness for applicable use in each case; (iv) Outputs may have different results based on the formulation of questions or the information provided as input; and (v) you will not use or allow your end-users to use the Product to generate Outputs that violate another person&apos;s rights, including, without limitation, by way of an infringement of intellectual property rights.
              </p>
            </section>

            <section>
              <h3 className="mb-2 text-base font-bold text-slate-900 dark:text-slate-100">
                3. User Responsibility:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                It is the responsibility of the user to apply their own professional judgment and expertise when using this Product. Any decisions made based on the responses generated by the Product must be independently verified by the user, and the user should not rely solely on the Product for decision-making. You agree that you fully release and will not hold the Canadian Pharmacists Association (CPhA) (&quot;CPhA&quot;), Pharma Guide Inc. (&quot;PharmaGuide&quot;), or their respective affiliates, partners, employees, or agents liable for any errors, omissions, or inaccuracies in the information provided by the Product.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                The Product does not, and is not intended to, replace any pharmacists or clinical providers, and is not intended to be used to make any medical diagnoses. The Product and Outputs provided in connection therewith are not a substitute for the competent analysis and professional judgment of a healthcare professional and are not intended to replace medical consultation, examination, record review, or applicable drug assessments. YOU ARE RESPONSIBLE FOR THE FINAL REVIEW OF OUTPUTS GENERATED BY THE PRODUCT AND ALL DECISION-MAKING THEREIN. THE PROFESSIONAL DUTY TO ANY PATIENTS IN THE PROVISION OF HEALTH CARE SERVICES REMAINS SOLELY WITH YOU AND NOT WITH CPHA OR PHARMAGUIDE.
              </p>
            </section>

            <section>
              <h3 className="mb-2 text-base font-bold text-slate-900 dark:text-slate-100">
                4. No Liability:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                IN NO EVENT SHALL CPHA, PHARMAGUIDE OR ANY OF THEIR RESPECTIVE AFFILIATES OR ITS OR THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, SUBCONTRACTORS, MEMBERS, SHAREHOLDERS, LEGAL REPRESENTATIVES, AGENTS, SUCCESSORS OR ASSIGNS (COLLECTIVELY &quot;REPRESENTATIVES&quot;) BE LIABLE FOR: (A) LOSS OF REVENUES, PROFITS, CONTRACTS, BUSINESS, GOODWILL OR ANTICIPATED SAVINGS, OR (B) ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE, EXEMPLARY OR OTHER LOSSES OR DAMAGE WHATSOEVER, WHETHER IN CONTRACT, TORT OR OTHERWISE (INCLUDING IN EACH CASE NEGLIGENCE), EVEN IF SUCH LOSSES WERE REASONABLY FORESEEABLE OR CPHA, PHARMAGUIDE OR ANY OF THEIR RESPECTIVE AFFILIATES OR ITS OR THEIR REPRESENTATIVES HAD BEEN ADVISED OF THE POSSIBILITY OF THE OTHER PARTY INCURRING THE SAME.
              </p>
            </section>

            <section>
              <h3 className="mb-2 text-base font-bold text-slate-900 dark:text-slate-100">
                5. Feedback Collection:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                During the testing phase, CPhA and PharmaGuide may collect data, including user feedback, error reports, and usage patterns, to improve the Product. By using this Product, you consent to the collection and use of this data for product refinement purposes. Any suggestions or feedback you provide may be used without compensation or acknowledgment, and you waive any claim to any intellectual property rights or compensation for your suggestions or feedback, and hereby assign all such rights to CPhA and PharmaGuide. We will have full discretion to determine whether or not to proceed with the development of any requested enhancements, new features or functionality.
              </p>
            </section>

            <section>
              <h3 className="mb-2 text-base font-bold text-slate-900 dark:text-slate-100">
                6. Acceptance and Amendment of Disclaimer:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                By using this Product, you agree to this Disclaimer. We may amend, adapt or supplement this Disclaimer at any time without notice. Your continued use of the Product constitutes your acceptance of this Disclaimer, as amended. If you do not agree with this Disclaimer, you must immediately stop using the Product.
              </p>
            </section>

            <section>
              <h3 className="mb-2 text-base font-bold text-slate-900 dark:text-slate-100">
                7. Professional and Legal Use:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                The Product is intended to serve as an educational resource. The Outputs generated by this Product should not be interpreted as legal, medical, or professional advice and should not be used as a substitute for such advice. Users are expected to comply with all applicable laws, regulations, and professional standards when using the Product. CPhA and PharmaGuide are not responsible for ensuring that the content or Outputs generated comply with applicable laws or professional guidelines. The Product should only be used by medical professionals or healthcare providers. Patient assessment requires professional knowledge and judgment beyond the scope of the Product.
              </p>
            </section>

            <section>
              <h3 className="mb-2 text-base font-bold text-slate-900 dark:text-slate-100">
                8. Modifications and Termination:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                CPhA and PharmaGuide reserve the right to modify, suspend, or discontinue the Product at any time without notice. Updates or changes to the Product may include changes to its features, functionality, or content.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                CPhA and PharmaGuide may terminate your access to the Product without notice at any time for any reason, including but not limited to if you violate any terms of this Disclaimer, or for no reason.
              </p>
            </section>

            <section>
              <h3 className="mb-2 text-base font-bold text-slate-900 dark:text-slate-100">
                9. DISCLAIMER OF WARRANTIES:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                THIS TEST PRODUCT IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; AND WITHOUT ANY WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING ALL STATUTORY WARRANTIES AND CONDITIONS. CPHA AND PHARMAGUIDE MAKE NO WARRANTIES REGARDING THE ACCURACY, RELIABILITY, COMPLETENESS, OR SUITABILITY OF THE PRODUCT FOR ANY PARTICULAR PURPOSE. ALL IMPLIED WARRANTIES AND CONDITIONS, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT, ARE HEREBY DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, CPHA AND PHARMAGUIDE DO NOT WARRANT THAT THE PRODUCT IS ERROR-FREE OR THAT THE PRODUCT WILL OPERATE WITHOUT INTERRUPTION. THE PRODUCT MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS. CPHA AND PHARMAGUIDE ARE NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES OR OTHER DAMAGES RESULTING FROM SUCH PROBLEMS. CPHA AND PHARMAGUIDE DO NOT WARRANT OR GUARANTEE THAT THE OUTPUTS OBTAINED THROUGH THE PRODUCT WILL BE ACCURATE, RELEVANT, COMPLETE, OR UP TO DATE. CPHA AND PHARMAGUIDE ARE NOT LIABLE OR RESPONSIBLE FOR, AND HEREBY EXPRESSLY DISCLAIM, UNDER ANY CIRCUMSTANCES: (A) HOW THE PRODUCT IS USED BY YOU OR YOUR END-USERS, (B) HOW YOU USE ANY INFORMATION, OUTPUTS OR DATA OBTAINED THROUGH THE PRODUCT, OR (C) ANY CONSEQUENCES THEREOF.
              </p>
            </section>

            <section>
              <h3 className="mb-2 text-base font-bold text-slate-900 dark:text-slate-100">
                10. General:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                This Disclaimer shall be governed by and construed in accordance with the laws of the Province of Ontario and the laws of Canada applicable therein. You agree to irrevocably attorn to the exclusive jurisdiction of the courts located in Ottawa, Ontario. If any part of this Disclaimer is held to be invalid or otherwise unenforceable, the provision shall no longer form part of this Disclaimer.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                By continuing to use this Product, you confirm that you have read, understood, and agree to this Disclaimer. If you do not agree, you must discontinue use of the Product immediately.
              </p>
            </section>
          </div>
        </div>

        {/* Checkbox */}
        <div className="border-t border-slate-200 px-6 py-3 dark:border-slate-700">
          <label className="flex cursor-pointer items-start gap-3">
            <input
              type="checkbox"
              checked={acknowledged}
              onChange={(e) => setAcknowledged(e.target.checked)}
              className="mt-0.5 h-5 w-5 cursor-pointer rounded border-slate-300 focus:ring-2 dark:border-slate-600 dark:bg-slate-800"
              style={{ accentColor: "#52B8C5" }}
            />
            <span className="text-sm text-slate-700 dark:text-slate-300">
              I acknowledge the above and agree to participate in feedback collection.
            </span>
          </label>
        </div>

        {/* Actions */}
        <div className="px-6 pb-6 pt-2">
          <button
            onClick={handleConfirm}
            disabled={!acknowledged}
            className="w-full rounded-lg px-4 py-3 text-sm font-medium text-white transition-colors disabled:cursor-not-allowed disabled:opacity-50"
            style={{
              backgroundColor: acknowledged ? "#52B8C5" : "#94a3b8",
            }}
          >
            CONFIRM AND PROCEED
          </button>
        </div>
      </div>
    </div>
  );
}
